on:
  push:
    branches:
      - main
      - master
  pull_request:


name: test
jobs:
  test-nocache:
    strategy:
      matrix:
        go-version: [stable, 1.22.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false
    - run: go test ./...
